# Generated by Django 4.2.7 on 2023-12-04 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0003_rename_create_date_question_create_dat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='create_dat',
            new_name='create_date',
        ),
    ]
