# Generated by Django 4.2.7 on 2023-12-07 06:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pybo', '0004_rename_create_dat_question_create_date'),
    ]

    operations = [
        # migrations.RenameField(
        #     model_name='answer',
        #     old_name='create_date',
        #     new_name='create_date',
        # ),
        migrations.AddField(
            model_name='question',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
