# Generated by Django 4.2.7 on 2023-12-07 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0005_rename_creat_date_answer_create_date_question_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='author',
        ),
    ]
