# Generated by Django 4.2.7 on 2023-12-07 13:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pybo', '0008_rename_creat_date_answer_create_date_and_more'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='answer',
        #     name='creat_date',
        # ),
        migrations.AddField(
            model_name='answer',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        # migrations.AddField(
        #     model_name='answer',
        #     name='create_date',
        #     field=models.DateField(default=1),
        #     preserve_default=False,
        # ),
    ]
