# Generated by Django 4.2.7 on 2023-12-07 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0009_remove_answer_creat_date_answer_author_and_more'),
    ]

    operations = [
        # migrations.RenameField(
        #     model_name='answer',
        #     old_name='creat_date',
        #     new_name='create_date',
        # ),
    ]
