# Generated by Django 4.2.7 on 2023-12-07 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0010_rename_creat_date_answer_create_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='creat_date',
            new_name='create_date',
        ),
    ]
